spring:
  application:
    name:
      eureka-server
server:
  port: 1001

eureka:
  instance:
    hostname : localhost
  client:
    register-with-eureka: false #false:不作为一个客户端注册到注册中心
    fetch-registry: false
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    instance:
        hostname: localhost
    server:  #配置属性，但由于 Eureka 自我保护模式以及心跳周期长的原因，经常会遇到 Eureka Server 不剔除已关停的节点的问题
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 5000